@echo off
echo Unpacking UiPath packages...
7za x -r -aoa "..\packages\UiPath*" -o"..\bin"
echo Copying needed dll-files...
copy "..\bin\lib\*.dll" "..\bin\build" /Y
echo Copying the bat-file for starting UiExplorer.exe...
copy "UiExplorer.bat" ".." /Y